### ISSUE TITLE
dtoolcore.generate_manifest logs to root logger rather than dtoolcore logger

### ISSUE THREAD

**Issue by mrmh2** [jic-dtool/dtoolcore#16]
The line:

https://github.com/jic-dtool/dtoolcore/blob/b0fbc034d60834a7acdf757fb8a865ea0e7a7689/dtoolcore/__init__.py#L442

should probably be:

``
            logger.info(
``

**Comment by tjelvar-olsson** [comment]
This seems to have been fixed at some point. Closing.
